// Headless gates for the pay page's issuance decision (src/lib/pay.ts) over a
// fake fetch — no server, no DOM. What is gated:
//
//   (1) ORDER + WIRE — one load resolves the record then POSTs the announce
//       with EXACTLY the derivation of the drawn scalar; the returned
//       destination equals the local CREATE2 mapping (which the committed
//       parity vector pins to the Solidity factory, so the page shows the
//       address the chain would derive).
//   (2) ANNOUNCE-BEFORE-DISPLAY — a failed announce means NO display data:
//       issuePayment rejects, so the caller can never render an unrecorded
//       address.
//   (3) PARITY FAIL-CLOSED — a server destination that disagrees with the
//       local mapping (hostile/misconfigured indexer) rejects.
//   (4) RECORD VALIDATION — unregistered labels and records without the v2
//       consumer pair (or with the zero-sentinel clear) refuse before any
//       derivation happens.
//
//   node --import tsx --test test/pay.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";

import {
  create2Address,
  deriveStealthAddress,
  portalSalt,
  stealthKeysFromScalars,
} from "@bongtu/core/stealth";
import { KEM_EK_ZERO, NOTE_VIEW_PUB_ZERO } from "@bongtu/core/eddsa";
import type { NameRecord } from "@bongtu/core/indexerApi";

import { issuePayment, labelFromPath, recordProblem, shortAddress, type PayDeps } from "../src/lib/pay.js";

// The committed TS<->Solidity parity constants (packages/core/test/stealth.test.ts,
// generated by chains/evm/test/PortalPriv.t.sol) — using them here means the
// destination this suite accepts is the one the REAL PortalPrivFactory derives.
const FACTORY = "0x00000000000000000000000000000000c0ffee02";
const INITCODE_HASH = "0x4a892b03a9bed6cf542e81c3167c1d8133dc50e3a2f7944230d99d870741e9c0";

const META = stealthKeysFromScalars(3333n, 4444n).meta;
const SCALAR = 987654321987654321n;

const RECORD: NameRecord = {
  name: "jun",
  owner: "0x" + "11".repeat(32),
  viewPub: META.viewPub,
  spendPub: META.spendPub,
  noteViewPub: "0x" + "22".repeat(32),
  kemEk: "0x" + "33".repeat(1184),
  updatedAt: 1_700_000_000,
};

/** A fake fetch serving GET /names/{label} + POST /portal/announce, recording
 *  every call in order. The announce handler recomputes the destination the
 *  way the real server does (addressOf == create2Address over the salt). */
function fakeIndexer(over: {
  record?: NameRecord | null;
  announceStatus?: number;
  serveDestination?: (local: string) => string;
} = {}) {
  const calls: { method: string; url: string; body?: unknown }[] = [];
  const fetchFn = (async (input: unknown, init?: { method?: string; body?: string }) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    const body = init?.body ? JSON.parse(init.body) : undefined;
    calls.push({ method, url, body });
    if (url.includes("/names/")) {
      const record = over.record === undefined ? RECORD : over.record;
      return record
        ? new Response(JSON.stringify(record), { status: 200 })
        : new Response("name not registered", { status: 404 });
    }
    if (url.endsWith("/portal/announce")) {
      if (over.announceStatus) return new Response("refused", { status: over.announceStatus });
      const local = create2Address(FACTORY, portalSalt(body.stealthAddr), INITCODE_HASH);
      const destination = over.serveDestination ? over.serveDestination(local) : local;
      return new Response(
        JSON.stringify({
          kind: "portal", seq: 0, rail: "evm", factory: FACTORY,
          ephemeralPub: body.ephemeralPub, viewTag: body.viewTag,
          stealthAddr: body.stealthAddr, destination,
          createdAt: 1, swept: false, sweptTxHash: null, sweptAmount: null,
        }),
        { status: 200 },
      );
    }
    throw new Error(`unexpected fetch: ${method} ${url}`);
  }) as typeof fetch;
  return { fetchFn, calls };
}

function deps(fetchFn: typeof fetch): PayDeps {
  return {
    indexerUrl: "http://indexer",
    portalPrivFactory: FACTORY,
    sweeperInitCodeHash: INITCODE_HASH,
    fetchFn,
    drawScalar: () => SCALAR,
  };
}

test("one load: resolve -> announce with the exact derivation -> destination == local CREATE2 mapping", async () => {
  const { fetchFn, calls } = fakeIndexer();
  const issued = await issuePayment("jun", deps(fetchFn));

  const derived = deriveStealthAddress(META, SCALAR);
  assert.deepEqual(
    calls.map((c) => `${c.method} ${c.url}`),
    ["GET http://indexer/names/jun", "POST http://indexer/portal/announce"],
    "exactly resolve then announce, nothing else",
  );
  assert.deepEqual(calls[1].body, {
    label: "jun",
    ephemeralPub: derived.ephemeralPub,
    viewTag: derived.viewTag,
    stealthAddr: derived.address,
  });
  assert.equal(issued.destination, create2Address(FACTORY, portalSalt(derived.address), INITCODE_HASH));
  assert.equal(issued.stealthAddr, derived.address);
  assert.equal(issued.label, "jun");
});

test("a fresh scalar per load: two issuances differ in every derived field", async () => {
  const { fetchFn } = fakeIndexer();
  const d = deps(fetchFn);
  const scalars = [SCALAR, SCALAR + 1n];
  const draws = { i: 0 };
  d.drawScalar = () => scalars[draws.i++];
  const a = await issuePayment("jun", d);
  const b = await issuePayment("jun", d);
  assert.notEqual(a.destination, b.destination);
  assert.notEqual(a.stealthAddr, b.stealthAddr);
  assert.notEqual(a.ephemeralPub, b.ephemeralPub);
});

test("announce-before-display: a failed announce leaves NOTHING to render", async () => {
  const { fetchFn } = fakeIndexer({ announceStatus: 500 });
  await assert.rejects(() => issuePayment("jun", deps(fetchFn)), /500/);
  // The 409 duplicate (first write wins) is equally fatal to THIS load — the
  // visitor just reloads for a fresh derivation.
  const dup = fakeIndexer({ announceStatus: 409 });
  await assert.rejects(() => issuePayment("jun", deps(dup.fetchFn)), /409/);
});

test("parity fail-closed: a server destination differing from the local mapping rejects", async () => {
  const { fetchFn } = fakeIndexer({ serveDestination: () => "0x" + "99".repeat(20) });
  await assert.rejects(() => issuePayment("jun", deps(fetchFn)), /주소 확인에 실패/);
});

test("record validation: unregistered and consumer-pair-less records refuse before deriving", async () => {
  const none = fakeIndexer({ record: null });
  await assert.rejects(() => issuePayment("jun", deps(none.fetchFn)), /등록되지 않은/);
  assert.equal(none.calls.length, 1, "refusal happens before any announce");

  for (const broken of [
    { ...RECORD, noteViewPub: undefined, kemEk: undefined },
    { ...RECORD, noteViewPub: NOTE_VIEW_PUB_ZERO, kemEk: KEM_EK_ZERO },
  ]) {
    const { fetchFn, calls } = fakeIndexer({ record: broken as NameRecord });
    await assert.rejects(() => issuePayment("jun", deps(fetchFn)), /받을 준비/);
    assert.equal(calls.length, 1);
  }
});

test("unconfigured factory refuses without touching the network", async () => {
  const { fetchFn, calls } = fakeIndexer();
  const d = deps(fetchFn);
  d.portalPrivFactory = "";
  await assert.rejects(() => issuePayment("jun", d), /unconfigured/);
  assert.equal(calls.length, 0);
});

test("recordProblem covers the payability matrix", () => {
  assert.equal(recordProblem(RECORD), null);
  assert.notEqual(recordProblem(null), null);
  assert.notEqual(recordProblem({ ...RECORD, kemEk: KEM_EK_ZERO }), null);
});

test("labelFromPath parses /p/{label} and nothing else", () => {
  assert.equal(labelFromPath("/p/jun"), "jun");
  assert.equal(labelFromPath("/p/jun-frx"), "jun-frx");
  assert.equal(labelFromPath("/"), null);
  assert.equal(labelFromPath("/pay/jun"), null);
  assert.equal(labelFromPath("/p/jun/extra"), null);
});

test("shortAddress keeps head and tail", () => {
  assert.equal(shortAddress("0x7f3Aabcdefabcdefabcdefabcdefabcdefab9c4E"), "0x7f3A…9c4E");
});
