// gen_enterprise_vectors.ts — per-op mollusk harness fixtures for the S3
// enterprise instruction set (SOLR §3.3 / §5.2; OPEN-1: the full family),
// the enterprise sibling of gen_vectors.ts.
//
// Run from the repo root:
//   node_modules/.bin/tsx chains/solana/scripts/gen_enterprise_vectors.ts
//
// Reads   chains/evm/test/fixtures/realproofs.json          (committed EVM
//         enterprise realproof fixtures: deposit, withdraw, transfer,
//         transfer10x2 — kem-enveloped publics, one shared arbiter key),
//         chains/evm/test/fixtures/disburse256.oracle.json  (the GPU-proven
//         production-arity disburse fixture + its ImtTree(32,256) oracle),
//         chains/evm/test/fixtures/disburse256.input.json   (the witness
//         input the committed disburse256 proof was generated from — the
//         source the 2054-element disclosure blob is re-derived from),
//         circuits/fixtures/fixture_lib.ts                  (the fixture KEM
//         material + the shared fixture assertion vocabulary),
//         packages/core @bongtu/core/solana + solanaOps     (the rail facts
//         and the ONE per-op public-signal layout table)
// Writes  chains/solana/conformance/deposit_fixture.json
//         chains/solana/conformance/withdraw_fixture.json
//         chains/solana/conformance/transfer_fixture.json
//         chains/solana/conformance/transfer10x2_fixture.json
//         chains/solana/conformance/disburse256_fixture.json
//
// Every value is asserted against the fixture's own committed anchors before
// anything is written: membership-root and rootAfter replays through the
// ImtTree oracle, the enabled-derivation rule, the one-arbiter-key rule
// (every enterprise proof binds realproofs.arbiterKey — the Deploy.s.sol
// default, chain-agnostic bjj material), kemBinding vs the deterministic KEM
// draw, and disclosureChain(re-derived blob) == the proof's disclosureHash
// public (the packages/core envelope.test.ts p2 recipe). A drifted core or
// fixture fails here, not in mollusk. Public-signal positions come from the
// ONE layout table (@bongtu/core/solanaOps) — no local index literals.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ImtTree } from "@bongtu/core/imt";
import {
  authorityCiphertextLen,
  buildAuthorityPlaintext,
  disclosureChain,
} from "@bongtu/core/envelope";
import { hybridEnvelopeKey, kemBindingOf, kemBytesToHex } from "@bongtu/core/kem";
import { deriveKeypair, ecdhSharedSecret, poseidonEncrypt } from "@bongtu/core/note";
import type { Point } from "@bongtu/core/babyjub";
import { BATCH_B_ENTERPRISE, LOG_B_ENTERPRISE, TREE_HEIGHT } from "@bongtu/core/solana";
import { SOLANA_OPS, type SolanaOpLayout } from "@bongtu/core/solanaOps";

import {
  checkEnabled,
  checkKemCtHex,
  hex32,
  kemDraw,
  makeAssertEq,
  proofHex,
  snapshot,
  writeJson,
} from "../../../circuits/fixtures/fixture_lib.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..", "..");
const FIXTURES = join(REPO, "chains", "evm", "test", "fixtures");
const CONFORMANCE = join(HERE, "..", "conformance");

// Enterprise profile tree shape: height 32 protocol-wide, B=256 (the
// production disburse arity — Deploy.s.sol BATCH_SIZE default). LOG_B = 8.
const H = TREE_HEIGHT;
const B = BATCH_B_ENTERPRISE;
const LOG_B = LOG_B_ENTERPRISE;

const assertEq = makeAssertEq("gen_enterprise_vectors");

interface EvmFixture {
  a: string[];
  b: string[][];
  c: string[];
  pub: string[];
  seedLeaves?: string[];
  rootAfter: string;
  kemCiphertext: string;
  kemBinding: string;
}

/** The one-arbiter-key rule: every enterprise fixture proof binds the SAME
 *  key (realproofs.arbiterKey == the Deploy.s.sol default), at the layout
 *  table's injected authorityPubKey position. */
function checkArbiterKey(
  layout: SolanaOpLayout,
  pub: string[],
  key: [string, string],
  what: string,
): void {
  assertEq(BigInt(pub[layout.fields.authorityPubKey[0]]), BigInt(key[0]), `${what} arbiter key x`);
  assertEq(BigInt(pub[layout.fields.authorityPubKey[1]]), BigInt(key[1]), `${what} arbiter key y`);
}

function depositFixture(fx: EvmFixture, arbiterKey: [string, string]): object {
  const L = SOLANA_OPS.deposit;
  assertEq(fx.pub.length, L.nPublic, "deposit pub len");
  checkKemCtHex(fx.kemCiphertext, assertEq);
  assertEq(BigInt(fx.kemBinding), BigInt(fx.pub[L.fields.kemBinding[0]]), "deposit kemBinding public");
  checkArbiterKey(L, fx.pub, arbiterKey, "deposit");

  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const t = new ImtTree(H, B);
  const pre = snapshot(t);
  t.appendLeaf(BigInt(outputCommitments[0]));
  t.appendLeaf(BigInt(outputCommitments[1]));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(fx.rootAfter)), "deposit rootAfter replay");

  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_enterprise_vectors.ts from the committed EVM " +
      "enterprise deposit realproof fixture (chains/evm/test/fixtures/realproofs.json) + the " +
      "packages/core ImtTree oracle. Mollusk gates 2/5 input — SOLR §5.2.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: [fx.kemCiphertext],
    outputCommitments,
    amount: fx.pub[L.fields.amount[0]],
    newRoot: fx.rootAfter,
    startLeafIndex: 0,
    preState: pre,
    postState: post,
  };
}

// The fixture's recipient public is a uint160 EVM address; on this rail the
// program injects the OPEN-3 truncate-253 binding of the recipient token
// account, and any 253-bit value IS a reachable token-account address (top 3
// bits zero), so the SAME committed proof replays at op level with the
// recipient token account placed at address BE32(recipient public) — no
// re-proving (unlike withdrawPriv, whose op-level fixture needed a
// Solana-bound re-prove only because its S2 harness predates this trick and
// pins a realistic address).
function withdrawFixture(fx: EvmFixture, arbiterKey: [string, string]): object {
  const L = SOLANA_OPS.withdraw;
  assertEq(fx.pub.length, L.nPublic, "withdraw pub len");
  checkKemCtHex(fx.kemCiphertext, assertEq);
  assertEq(BigInt(fx.kemBinding), BigInt(fx.pub[L.fields.kemBinding[0]]), "withdraw kemBinding public");
  checkArbiterKey(L, fx.pub, arbiterKey, "withdraw");
  checkEnabled(fx.pub, L.enabled!, assertEq);
  const recipient = BigInt(fx.pub[L.fields.recipient[0]]);
  if (recipient === 0n || recipient >= 1n << 160n) {
    throw new Error("gen_enterprise_vectors: withdraw recipient public is not a uint160 address");
  }

  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  const changeCommitment = fx.pub[L.fields.changeCommitment[0]];
  const spentRoot = fx.pub[L.fields.root[0]];
  const t = new ImtTree(H, B);
  for (const leaf of fx.seedLeaves!) t.appendLeaf(BigInt(leaf));
  const pre = snapshot(t);
  assertEq(pre.currentRoot, hex32(BigInt(spentRoot)), "withdraw membership root replay");
  t.appendLeaf(BigInt(changeCommitment));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(fx.rootAfter)), "withdraw rootAfter replay");

  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_enterprise_vectors.ts from the committed EVM " +
      "enterprise withdraw realproof fixture + the packages/core ImtTree oracle. The recipient " +
      "token account address is BE32(pub[26]) so the truncate-253 binding reproduces the " +
      "proof-bound recipient exactly. Mollusk gates 2/5 input — SOLR §5.2.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: [fx.kemCiphertext],
    nullifiers,
    changeCommitment,
    amount: fx.pub[L.fields.amount[0]],
    recipientTokenAccount: hex32(recipient),
    stealthEphemeralPub: hex32(0n),
    stealthViewTag: 0,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

// Carried = the vector minus enabled[2] (program-derived) and the arbiter
// key (config-injected) = 33 publics (S3 pass 2 wire) — the layout table
// derives exactly that composition.
function transferFixture(fx: EvmFixture, arbiterKey: [string, string]): object {
  const L = SOLANA_OPS.transfer;
  assertEq(fx.pub.length, L.nPublic, "transfer pub len");
  checkKemCtHex(fx.kemCiphertext, assertEq);
  assertEq(BigInt(fx.kemBinding), BigInt(fx.pub[L.fields.kemBinding[0]]), "transfer kemBinding public");
  checkArbiterKey(L, fx.pub, arbiterKey, "transfer");
  checkEnabled(fx.pub, L.enabled!, assertEq);

  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const spentRoot = fx.pub[L.fields.root[0]];
  const t = new ImtTree(H, B);
  for (const leaf of fx.seedLeaves!) t.appendLeaf(BigInt(leaf));
  const pre = snapshot(t);
  assertEq(pre.currentRoot, hex32(BigInt(spentRoot)), "transfer membership root replay");
  t.appendLeaf(BigInt(outputCommitments[0]));
  t.appendLeaf(BigInt(outputCommitments[1]));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(fx.rootAfter)), "transfer rootAfter replay");

  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_enterprise_vectors.ts from the committed EVM " +
      "enterprise transfer realproof fixture (chains/evm/test/fixtures/realproofs.json) + the " +
      "packages/core ImtTree oracle. Mollusk gates 2/5 input — SOLR §5.2 (S3 pass 2).",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: [fx.kemCiphertext],
    nullifiers,
    outputCommitments,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

// The committed fixture is the MERGE entry (all 10 inputs real), so the
// op-level replay drives the full 10-nullifier-PDA shape — the worst-case
// account count gate 4 pins and the worst-case CU gate 3 records.
function transfer10x2Fixture(fx: EvmFixture, arbiterKey: [string, string]): object {
  const L = SOLANA_OPS.transfer10x2;
  assertEq(fx.pub.length, L.nPublic, "transfer10x2 pub len");
  checkKemCtHex(fx.kemCiphertext, assertEq);
  assertEq(BigInt(fx.kemBinding), BigInt(fx.pub[L.fields.kemBinding[0]]), "transfer10x2 kemBinding public");
  checkArbiterKey(L, fx.pub, arbiterKey, "transfer10x2");
  checkEnabled(fx.pub, L.enabled!, assertEq);
  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  assertEq(
    nullifiers.filter((nf) => BigInt(nf) !== 0n).length,
    10,
    "transfer10x2 fixture spends all 10 inputs (the merge entry)",
  );

  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const spentRoot = fx.pub[L.fields.root[0]];
  const t = new ImtTree(H, B);
  for (const leaf of fx.seedLeaves!) t.appendLeaf(BigInt(leaf));
  const pre = snapshot(t);
  assertEq(pre.currentRoot, hex32(BigInt(spentRoot)), "transfer10x2 membership root replay");
  t.appendLeaf(BigInt(outputCommitments[0]));
  t.appendLeaf(BigInt(outputCommitments[1]));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(fx.rootAfter)), "transfer10x2 rootAfter replay");

  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_enterprise_vectors.ts from the committed EVM " +
      "enterprise transfer10x2 MERGE realproof fixture (all 10 inputs real, so the op-level " +
      "replay exercises the full 10-nullifier-PDA shape) + the packages/core ImtTree oracle. " +
      "Mollusk gates 2/5 input — SOLR §5.2 (S3 pass 2).",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: [fx.kemCiphertext],
    nullifiers,
    outputCommitments,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

interface DisburseOracle {
  inputCommitment: string;
  seedRoot: string;
  oracleRoot: string;
  nextLeafIndexBeforeAttach: number;
  finalNextLeafIndex: number;
  arbiterKey: string[];
  a: string[];
  b: string[][];
  c: string[];
  pub: string[];
}

interface Disburse256Input {
  inputValues: string[];
  inputSalts: string[];
  inputOwnerPrivateKey: string;
  ecdhPrivateKey: string;
  encryptionNonce: string;
  outputValues: string[];
  outputSalts: string[];
  outputOwnerPublicKeys: [string, string][];
  authorityPublicKey: [string, string];
}

/** Re-derive the 65,728 B disclosure blob (receiverCts[1024] ++
 *  authorityEnvelope[1030]) from the committed witness input — the
 *  packages/core test/envelope.test.ts p2 recipe — and pin its fold to the
 *  proof's disclosureHash public. This blob is what the institution serves
 *  (SOLR §3.3.2); the refold gate checks it against DisburseBatch. */
function disclosureBlob(input: Disburse256Input, kemSs: [bigint, bigint]): bigint[] {
  const ecdh = BigInt(input.ecdhPrivateKey);
  const nonce = BigInt(input.encryptionNonce);
  const owners: Point[] = input.outputOwnerPublicKeys.map((p) => [BigInt(p[0]), BigInt(p[1])]);
  const receiverFlat = owners.flatMap((owner, i) =>
    poseidonEncrypt(
      [BigInt(input.outputValues[i]), BigInt(input.outputSalts[i])],
      ecdhSharedSecret(ecdh, owner),
      nonce,
    ),
  );
  const inOwner = deriveKeypair(BigInt(input.inputOwnerPrivateKey)).publicKey;
  const authPlain = buildAuthorityPlaintext("disburse", {
    inputs: [
      { owner: inOwner, value: BigInt(input.inputValues[0]), salt: BigInt(input.inputSalts[0]) },
    ],
    outputs: owners.map((owner, i) => ({
      owner,
      value: BigInt(input.outputValues[i]),
      salt: BigInt(input.outputSalts[i]),
    })),
  });
  const authorityCt = poseidonEncrypt(
    authPlain,
    hybridEnvelopeKey(
      ecdhSharedSecret(ecdh, [
        BigInt(input.authorityPublicKey[0]),
        BigInt(input.authorityPublicKey[1]),
      ]),
      kemSs,
    ),
    nonce,
  );
  const full = [...receiverFlat, ...authorityCt];
  assertEq(full.length, 4 * B + authorityCiphertextLen("disburse", B), "disclosure blob length");
  assertEq(full.length, 2054, "disclosure blob is 2054 elements");
  return full;
}

function disburse256Fixture(
  oracle: DisburseOracle,
  input: Disburse256Input,
  arbiterKey: [string, string],
): object {
  const L = SOLANA_OPS.disburse256;
  const pub = oracle.pub;
  assertEq(pub.length, L.nPublic, "disburse256 pub len");
  checkEnabled(pub, L.enabled!, assertEq); // constantOne: the enabled public is 1
  checkArbiterKey(L, pub, arbiterKey, "disburse256");
  assertEq(BigInt(oracle.arbiterKey[0]), BigInt(arbiterKey[0]), "oracle arbiter key x");
  assertEq(BigInt(oracle.arbiterKey[1]), BigInt(arbiterKey[1]), "oracle arbiter key y");

  const disclosureHash = pub[L.fields.disclosureHash[0]];
  const subtreeRoot = pub[L.fields.subtreeRoot[0]];
  const kemBinding = pub[L.fields.kemBinding[0]];
  const nullifier = pub[L.fields.nullifiers[0]];
  const spentRoot = pub[L.fields.root[0]];

  // The deterministic fixture KEM draw for this proof: the label-derived
  // encapsulation whose shared-secret limbs the witness carried, so the
  // 1088 B ct regenerates byte-stable and the binding pins it to the
  // kemBinding public.
  const draw = kemDraw("disburse256");
  assertEq(kemBindingOf(draw.kemSs), BigInt(kemBinding), "disburse256 kemBinding vs fixture KEM draw");
  const kemCiphertext = "0x" + kemBytesToHex(draw.kemCiphertext).replace(/^0x/, "");
  checkKemCtHex(kemCiphertext, assertEq);

  const blob = disclosureBlob(input, draw.kemSs);
  assertEq(disclosureChain(blob), BigInt(disclosureHash), "disclosureChain(blob) vs disclosureHash public");

  const t = new ImtTree(H, B);
  t.appendLeaf(BigInt(oracle.inputCommitment));
  const pre = snapshot(t);
  assertEq(pre.currentRoot, hex32(BigInt(spentRoot)), "disburse256 membership root replay");
  assertEq(pre.nextLeafIndex, oracle.nextLeafIndexBeforeAttach, "pre nextLeafIndex");
  t.attachSubtree(BigInt(subtreeRoot));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(oracle.oracleRoot)), "disburse256 oracleRoot replay");
  assertEq(post.nextLeafIndex, oracle.finalNextLeafIndex, "post nextLeafIndex");

  // Sub-LOG_B frontier splice: the program's attach closes the pending
  // partial block in O(LOG_B) folds and leaves filled_subtrees[i < LOG_B]
  // STALE (the EVM _attachSubtree shape — reads them, never writes), while
  // the JS oracle pads leaf-by-leaf and rewrites them. Both yield the same
  // root and the same frontier at levels >= LOG_B; the expected post-state
  // account image therefore carries the PRE values below LOG_B.
  const postProgram = {
    ...post,
    filledSubtrees: post.filledSubtrees.map((s, i) => (i < LOG_B ? pre.filledSubtrees[i] : s)),
  };

  const start = post.nextLeafIndex - B;
  assertEq(start, 256, "batch start leaf index");
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_enterprise_vectors.ts from the committed GPU " +
      "disburse256 fixture (chains/evm/test/fixtures/disburse256.{oracle,input}.json) + the " +
      "packages/core ImtTree oracle and envelope.ts disclosureChain (the test/envelope.test.ts " +
      "p2 recipe). disclosureElements is the 2054-element served-blob fixture the refold gate " +
      "checks against DisburseBatch.disclosureHash — SOLR §3.3.2 / §5.2. postState carries the " +
      "program's stale sub-LOG_B frontier (see the generator's splice note).",
    proof: proofHex(oracle, assertEq),
    publicsCarried: L.carried.map((i) => pub[i]),
    publicsFull: pub,
    kemCiphertexts: [kemCiphertext],
    nullifier,
    spentRoot,
    subtreeRoot,
    disclosureHash,
    kemBinding,
    newRoot: hex32(BigInt(oracle.oracleRoot)),
    startLeafIndex: start,
    batchEpoch: 0,
    preState: pre,
    postState: postProgram,
    disclosureElements: blob.map(hex32),
  };
}

function main(): void {
  const real = JSON.parse(readFileSync(join(FIXTURES, "realproofs.json"), "utf8")) as {
    deposit: EvmFixture;
    withdraw: EvmFixture;
    transfer: EvmFixture;
    transfer10x2_merge: EvmFixture;
    arbiterKey: [string, string];
  };
  const oracle = JSON.parse(
    readFileSync(join(FIXTURES, "disburse256.oracle.json"), "utf8"),
  ) as DisburseOracle;
  const input = JSON.parse(
    readFileSync(join(FIXTURES, "disburse256.input.json"), "utf8"),
  ) as Disburse256Input;

  writeJson(CONFORMANCE, "deposit_fixture.json", depositFixture(real.deposit, real.arbiterKey));
  writeJson(CONFORMANCE, "withdraw_fixture.json", withdrawFixture(real.withdraw, real.arbiterKey));
  writeJson(CONFORMANCE, "transfer_fixture.json", transferFixture(real.transfer, real.arbiterKey));
  writeJson(
    CONFORMANCE,
    "transfer10x2_fixture.json",
    transfer10x2Fixture(real.transfer10x2_merge, real.arbiterKey),
  );
  writeJson(
    CONFORMANCE,
    "disburse256_fixture.json",
    disburse256Fixture(oracle, input, real.arbiterKey),
  );
  console.log(
    "wrote deposit_fixture.json, withdraw_fixture.json, transfer_fixture.json, " +
      "transfer10x2_fixture.json, disburse256_fixture.json (anchors verified)",
  );
}

main();
