// gen_vectors.ts — export the shared-algebra vectors the Solana rail pins
// against (SOLR §4.1: the Rust TreeState is a third implementation of a
// twice-pinned algebra; SOLR §3.1.3 gate 1: poseidon conformance vectors) and
// the per-op harness fixtures for mollusk gates 2/3/5 (SOLR §5.2 state-level
// replay of the committed realproof fixtures).
//
// Run from the repo root:
//   node_modules/.bin/tsx chains/solana/scripts/gen_vectors.ts
//
// Reads   packages/core (poseidon + ImtTree — the JS oracle; the rail facts
//         and the per-op layout table: @bongtu/core/solana + solanaOps),
//         circuits/fixtures/fixture_lib.ts (the shared fixture assertion
//         vocabulary),
//         chains/evm/test/fixtures/consumer_realproofs.json (committed EVM
//         realproof fixtures: depositPriv, transferPriv, transfer10x2Priv),
//         chains/evm/test/fixtures/consumer_realproofs_solana.json (the ONE
//         re-proven withdrawPriv fixture, Solana-bound recipient — SOLR §5.2)
// Writes  chains/solana/conformance/poseidon_vectors.json    (gate 1 vectors)
//         chains/solana/conformance/<op>_priv_fixture.json x4 (gates 2/3/5
//                                                             harness input)
//         chains/solana/program/src/generated/zeros.rs       (IMT empty-subtree
//                                                             constants)
//
// Every value is asserted against the fixture's own committed anchors (the
// membership-root public, rootAfter, the enabled-derivation rule, the OPEN-3
// recipient binding) before anything is written — a drifted core or fixture
// fails here, not in mollusk. Public-signal positions come from the ONE
// layout table (@bongtu/core/solanaOps), the same table the ledger decoder
// consumes — no local index literals.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ImtTree } from "@bongtu/core/imt";
import { poseidon2, poseidonN } from "@bongtu/core/poseidon";
import { BATCH_B_CONSUMER, TREE_HEIGHT } from "@bongtu/core/solana";
import { SOLANA_OPS } from "@bongtu/core/solanaOps";

import {
  checkEnabled,
  checkKemCts,
  hex32,
  makeAssertEq,
  proofHex,
  snapshot,
  writeJson,
  type TreeSnapshot,
} from "../../../circuits/fixtures/fixture_lib.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..", "..");
const FIXTURE = join(REPO, "chains", "evm", "test", "fixtures", "consumer_realproofs.json");
const FIXTURE_SOLANA = join(
  REPO,
  "chains",
  "evm",
  "test",
  "fixtures",
  "consumer_realproofs_solana.json",
);
const CONFORMANCE = join(HERE, "..", "conformance");
const GENERATED = join(HERE, "..", "program", "src", "generated");

// Tree shape: height 32 shared protocol-wide; B=16 is the consumer fixture
// profile (gen_consumer_realproofs.ts seeds with ImtTree(32, 16)). The P2P
// ops never batch-attach, so B only labels the profile here.
const H = TREE_HEIGHT;
const B = BATCH_B_CONSUMER;

// docs/protocol.md parity anchor: Poseidon([1, 2]).
const CANONICAL_1_2 =
  7853200120776062878684798364095072458815029376092732009249414926327459813530n;

const dec = (v: bigint): string => v.toString(10);
const assertEq = makeAssertEq("gen_vectors");

// --- gate 1: poseidon conformance vectors (arity 2..5) ----------------------
function poseidonVectors(): object {
  if (poseidon2(1n, 2n) !== CANONICAL_1_2) {
    throw new Error("gen_vectors: packages/core poseidon2(1,2) drifted from docs/protocol.md");
  }
  // Hex (32-byte BE) alongside decimal: the Rust gate consumes hex directly
  // (no bigint dep); decimal keeps the vectors eyeball-comparable to
  // docs/protocol.md and the circom fixtures.
  const cases: { arity: number; inputs: string[]; inputsHex: string[]; out: string; outHex: string }[] =
    [];
  for (const arity of [2, 3, 4, 5]) {
    const seq = Array.from({ length: arity }, (_, i) => BigInt(i + 1)); // [1..n]
    const zero = Array.from({ length: arity }, () => 0n);
    const mixed = Array.from({ length: arity }, (_, i) => CANONICAL_1_2 + BigInt(i)); // large elements
    for (const inputs of [seq, zero, mixed]) {
      const out = poseidonN(inputs);
      cases.push({
        arity,
        inputs: inputs.map(dec),
        inputsHex: inputs.map(hex32),
        out: dec(out),
        outHex: hex32(out),
      });
    }
  }
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_vectors.ts from packages/core (poseidon-lite). " +
      "sol_poseidon(Bn254X5, BigEndian) must reproduce every `out` — SOLR §3.1.3 gate 1.",
    canonical_1_2: dec(CANONICAL_1_2),
    cases,
  };
}

// --- zeros.rs: empty-subtree chain zeros[0..=H] -----------------------------
function zerosRs(zeros: bigint[]): string {
  const rows = zeros
    .map((z) => {
      const h = z.toString(16).padStart(64, "0");
      const bytes = Array.from({ length: 32 }, (_, i) => `0x${h.slice(2 * i, 2 * i + 2)}`);
      return `    [${bytes.join(", ")}],`;
    })
    .join("\n");
  return `// GENERATED by chains/solana/scripts/gen_vectors.ts from packages/core ImtTree
// — DO NOT EDIT. zeros[k] = value of an all-empty subtree of height k:
// zeros[0] = 0, zeros[k] = Poseidon2(zeros[k-1], zeros[k-1]). Big-endian.
// Regenerate: node_modules/.bin/tsx chains/solana/scripts/gen_vectors.ts

/// IMT height (levels above the leaves) — shared protocol-wide (SOLR §4.1).
pub const TREE_HEIGHT: usize = ${H};

/// zeros[0..=TREE_HEIGHT]; zeros[TREE_HEIGHT] is the empty-tree root.
pub const ZEROS: [[u8; 32]; ${H + 1}] = [
${rows}
];
`;
}

// --- gates 2/3/5: per-op fixtures, Solana wire + state shape ----------------

interface EvmFixture {
  a: string[];
  b: string[][];
  c: string[];
  pub: string[];
  seedLeaves?: string[];
  rootAfter: string;
  kemCiphertexts: string[];
}

/** Replay a fixture's tree with the JS oracle: seed leaves (asserting the
 *  membership-root public), append the outputs (asserting rootAfter). */
function replay(
  fx: EvmFixture,
  seed: string[],
  rootPub: string | null,
  appends: string[],
): { pre: TreeSnapshot; post: TreeSnapshot } {
  const t = new ImtTree(H, B);
  for (const leaf of seed) t.appendLeaf(BigInt(leaf));
  const pre = snapshot(t);
  if (rootPub !== null) assertEq(pre.currentRoot, hex32(BigInt(rootPub)), "seeded root vs root public");
  for (const leaf of appends) t.appendLeaf(BigInt(leaf));
  const post = snapshot(t);
  assertEq(post.currentRoot, hex32(BigInt(fx.rootAfter)), "post-append root vs rootAfter");
  return { pre, post };
}

// transferPriv: layout @bongtu/core/solanaOps (full publics field map +
// carried composition + enabled derivation — one owner with the decoder).
function transferFixture(fx: EvmFixture): object {
  const L = SOLANA_OPS.transferPriv;
  assertEq(fx.pub.length, L.nPublic, "transferPriv pub len");
  checkKemCts(fx.kemCiphertexts, L.kemCtCount, assertEq);
  checkEnabled(fx.pub, L.enabled!, assertEq);
  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const spentRoot = fx.pub[L.fields.root[0]];
  const { pre, post } = replay(fx, fx.seedLeaves!, spentRoot, outputCommitments);
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_vectors.ts from the committed EVM transferPriv " +
      "realproof fixture (chains/evm/test/fixtures/consumer_realproofs.json) + the " +
      "packages/core ImtTree oracle. Mollusk gates 2/5 input — SOLR §5.2.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: fx.kemCiphertexts,
    nullifiers,
    outputCommitments,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

// depositPriv: a 0-in mint — nothing injected, ALL publics carried; tree
// starts empty (the fixture's own seed shape).
function depositFixture(fx: EvmFixture): object {
  const L = SOLANA_OPS.depositPriv;
  assertEq(fx.pub.length, L.nPublic, "depositPriv pub len");
  checkKemCts(fx.kemCiphertexts, L.kemCtCount, assertEq);
  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const { pre, post } = replay(fx, [], null, outputCommitments);
  assertEq(pre.nextLeafIndex, 0, "depositPriv pre-state is the empty tree");
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_vectors.ts from the committed EVM depositPriv " +
      "realproof fixture + the packages/core ImtTree oracle. Mollusk gates 2/5 input.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: fx.kemCiphertexts,
    outputCommitments,
    amount: fx.pub[L.fields.amount[0]],
    newRoot: fx.rootAfter,
    startLeafIndex: 0,
    preState: pre,
    postState: post,
  };
}

function transfer10x2Fixture(fx: EvmFixture): object {
  const L = SOLANA_OPS.transfer10x2Priv;
  assertEq(fx.pub.length, L.nPublic, "transfer10x2Priv pub len");
  checkKemCts(fx.kemCiphertexts, L.kemCtCount, assertEq);
  checkEnabled(fx.pub, L.enabled!, assertEq);
  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  const outputCommitments = L.fields.outputCommitments.map((i) => fx.pub[i]);
  const spentRoot = fx.pub[L.fields.root[0]];
  const { pre, post } = replay(fx, fx.seedLeaves!, spentRoot, outputCommitments);
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_vectors.ts from the committed EVM transfer10x2Priv " +
      "realproof fixture + the packages/core ImtTree oracle. Mollusk gates 2/5 input.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: fx.kemCiphertexts,
    nullifiers,
    outputCommitments,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

// withdrawPriv. Source: the ONE re-proven Solana-recipient fixture
// (consumer_realproofs_solana.json); the recipient public must equal the
// OPEN-3 truncate-253 binding of its recipientTokenAccount.
function withdrawFixture(
  fx: EvmFixture & {
    recipientTokenAccount: string;
    stealthEphemeralPub: string;
    stealthViewTag: number;
  },
): object {
  const L = SOLANA_OPS.withdrawPriv;
  assertEq(fx.pub.length, L.nPublic, "withdrawPriv pub len");
  checkKemCts(fx.kemCiphertexts, L.kemCtCount, assertEq);
  checkEnabled(fx.pub, L.enabled!, assertEq);

  const addr = BigInt(fx.recipientTokenAccount);
  assertEq((fx.recipientTokenAccount.length - 2) / 2, 32, "recipient token account length");
  const bound = addr & ((1n << 253n) - 1n);
  assertEq(
    BigInt(fx.pub[L.fields.recipient[0]]),
    bound,
    "recipient public vs truncate-253 recipient binding",
  );
  assertEq((fx.stealthEphemeralPub.length - 2) / 2, 32, "stealth ephemeral pub length");

  const nullifiers = L.fields.nullifiers.map((i) => fx.pub[i]);
  const changeCommitment = fx.pub[L.fields.changeCommitment[0]];
  const spentRoot = fx.pub[L.fields.root[0]];
  const { pre, post } = replay(fx, fx.seedLeaves!, spentRoot, [changeCommitment]);
  return {
    comment:
      "GENERATED by chains/solana/scripts/gen_vectors.ts from the re-proven Solana-recipient " +
      "withdrawPriv fixture (chains/evm/test/fixtures/consumer_realproofs_solana.json) + " +
      "the packages/core ImtTree oracle. Mollusk gates 2/5 input — SOLR §5.2's one exception.",
    proof: proofHex(fx, assertEq),
    publicsCarried: L.carried.map((i) => fx.pub[i]),
    publicsFull: fx.pub,
    kemCiphertexts: fx.kemCiphertexts,
    nullifiers,
    changeCommitment,
    amount: fx.pub[L.fields.amount[0]],
    recipientTokenAccount: fx.recipientTokenAccount,
    stealthEphemeralPub: fx.stealthEphemeralPub,
    stealthViewTag: fx.stealthViewTag,
    spentRoot,
    newRoot: fx.rootAfter,
    startLeafIndex: pre.nextLeafIndex,
    preState: pre,
    postState: post,
  };
}

function main(): void {
  const zeros = new ImtTree(H, B).zeros;
  writeFileSync(join(GENERATED, "zeros.rs"), zerosRs(zeros));
  writeJson(CONFORMANCE, "poseidon_vectors.json", poseidonVectors());

  const evm = JSON.parse(readFileSync(FIXTURE, "utf8")) as Record<string, EvmFixture>;
  const sol = JSON.parse(readFileSync(FIXTURE_SOLANA, "utf8")) as {
    withdrawPriv: EvmFixture & {
      recipientTokenAccount: string;
      stealthEphemeralPub: string;
      stealthViewTag: number;
    };
  };
  writeJson(CONFORMANCE, "deposit_priv_fixture.json", depositFixture(evm.depositPriv));
  writeJson(CONFORMANCE, "transfer_priv_fixture.json", transferFixture(evm.transferPriv));
  writeJson(CONFORMANCE, "transfer10x2_priv_fixture.json", transfer10x2Fixture(evm.transfer10x2Priv));
  writeJson(CONFORMANCE, "withdraw_priv_fixture.json", withdrawFixture(sol.withdrawPriv));
  console.log(
    "wrote zeros.rs, poseidon_vectors.json, {deposit,transfer,transfer10x2,withdraw}_priv_fixture.json (anchors verified)",
  );
}

main();
