// Solana-backend conformance leg (SOLR §5.3 / S4 row of issue #8's plan) —
// driven ENTIRELY by recorded ledger fixtures (chains/solana/conformance/
// ledger_*.json, generated by the harness record_ledger bin): no validator,
// no anvil — only the throwaway Postgres run.sh provisions. What it pins:
//
//   1. the applyLedgerTxs seam (the applyLogs double): signature-cursor
//      ingest, program-id + discriminator dispatch over top-level AND inner
//      instructions (foreign SPL CPIs in the record must be skipped), self-CPI
//      event decode, and the PER-OP mirror assertion (event resulting root);
//   2. read-model parity: the SAME routes the EVM leg serves — /head /events
//      /path /nullifiers /announcements — carry the consumer discovery
//      material (viewTags, kem cts, slices) in the identical wire shape;
//   3. the public self-scan feed end to end: the client selfscan engine
//      (@bongtu/client/selfscan, UNCHANGED) discovers a consumer note from
//      the recorded ledger through the live HTTP feed with only the wallet's
//      keys — the fixtures' recipients re-derive from circuits/fixtures
//      consumer_lib, the same PRNG-free plan the committed proofs encrypt to;
//   4. kill-and-resume: a restart rebuilds from Postgres, its frontier equals
//      the recorded TreeState at the stored cursor, and the re-ingest asks
//      the chain only for the signature GAP — then serves byte-identical
//      /events;
//   5. disclosure serving + alarm mapping (SOLR §3.3.2): the enterprise leg's
//      disburse verifies the institution-held blob against the chain-committed
//      hash (boot invariant), GET /disclosure serves it, a tampered blob maps
//      to the existing "mismatch" class, non-serving past grace to "withheld",
//      and the served-blob verifier inherits the gate-6 negative vectors
//      (non-canonical alias rejected BEFORE folding; order sensitivity)
//      against the one disclosureChain implementation;
//   6. dispatch shapes beyond single-op txs: a multi-op tx pairs ops with
//      events FIFO (an event-stripped record throws the imbalance), the
//      wrapper-invoked INNER withdrawPriv reaches the read model with its
//      meta-11 recipient on /announcements, a chain advancing between
//      txsSince and the head read is a benign next-poll condition (cursor
//      advances, health stays ok), and AUTHORITY_KEY refuses to boot (no
//      arbiter surfaces on this backend yet);
//   7. serve integrity: GET /disclosure always carries the chain-committed
//      hash and the registry's current verdict, a non-passing held blob is
//      409 (never a clean 200), and a blob swapped after its ingest-time
//      refold passed surfaces at the next boot as a registry-owned mismatch
//      alarm.
//
//   TEST_DATABASE_URL=... node --import tsx test/solana.test.ts   # (== npm run test:solana)

import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";

import { packPubkey } from "@bongtu/core/pubkey";
import { foldToRoot } from "@bongtu/core/imt";
import { FIELD_PRIME } from "@bongtu/core/poseidon";
import { runSelfScan, EMPTY_SCAN_STATE, type SelfScanIo, type SelfScanState } from "@bongtu/client/selfscan";
import type { ConsumerWalletIdentity } from "@bongtu/client/derive";

import { SolanaIndexer, type SolanaChainIo } from "../src/solana/ingest.js";
import { EVENT_DISCRIMINATOR, type SolanaLedgerTx } from "../src/solana/wire.js";
import { verifyServedDisclosure } from "../src/disclosure.js";
import { startApi } from "../src/api/router.js";
import type { ChainConfig } from "../src/chain.js";
import { consumerReceiver, CONSUMER_SENDER, type ConsumerIdentity } from "../../../circuits/fixtures/consumer_lib.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");
const CONFORMANCE = join(ROOT, "chains", "solana", "conformance");

const failures = { count: 0 };
function ok(cond: unknown, msg: string): void {
  const pass = !!cond;
  if (!pass) failures.count++;
  console.log(`   ${pass ? "PASS" : "FAIL"}  ${msg}`);
  if (!pass) throw new Error(`assertion failed: ${msg}`);
}
function step(t: string): void {
  console.log(`\n=== ${t} ===`);
}

const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;
if (!TEST_DATABASE_URL) {
  console.error("FATAL: TEST_DATABASE_URL is not set — the Solana conformance leg is Postgres-backed (run via test/run.sh, which provisions a throwaway postgres, or export TEST_DATABASE_URL yourself).");
  process.exit(1);
}

async function freshDatabase(name: string): Promise<string> {
  const admin = new Pool({ connectionString: TEST_DATABASE_URL });
  try {
    await admin.query(`DROP DATABASE IF EXISTS ${name}`);
    await admin.query(`CREATE DATABASE ${name}`);
  } finally {
    await admin.end();
  }
  const u = new URL(TEST_DATABASE_URL!);
  u.pathname = `/${name}`;
  return u.toString();
}

async function get(base: string, path: string): Promise<{ status: number; body: unknown }> {
  const r = await fetch(base + path);
  return { status: r.status, body: await r.json() };
}

// --- recorded-ledger fixtures -----------------------------------------------

interface RecordedTx extends SolanaLedgerTx {
  treeStatePost: { nextLeafIndex: number; currentRoot: string };
}
interface RecordedLedger {
  programId: string;
  batchB: number;
  txs: RecordedTx[];
  final: { nextLeafIndex: number; currentRoot: string };
}

const loadLedger = (name: string): RecordedLedger =>
  JSON.parse(readFileSync(join(CONFORMANCE, name), "utf8")) as RecordedLedger;

/** The recorded-ledger chain double (SOLR §5.3: no validator in the loop).
 *  `calls` records every txsSince cursor — the gap-only-resume witness. */
class FixtureChain implements SolanaChainIo {
  readonly calls: (string | null)[] = [];
  constructor(private readonly txs: RecordedTx[], private readonly b: number) {}
  async batchSize(): Promise<number> {
    return this.b;
  }
  async treeHead(): Promise<{ root: bigint; nextLeafIndex: number }> {
    const last = this.txs[this.txs.length - 1].treeStatePost;
    return { root: BigInt(last.currentRoot), nextLeafIndex: last.nextLeafIndex };
  }
  async txsSince(untilSignature: string | null): Promise<SolanaLedgerTx[]> {
    this.calls.push(untilSignature);
    if (untilSignature === null) return this.txs;
    const at = this.txs.findIndex((t) => t.signature === untilSignature);
    if (at === -1) throw new Error(`FixtureChain: unknown cursor signature ${untilSignature}`);
    return this.txs.slice(at + 1);
  }
}

const cfgOf = (databaseUrl: string, extra: Partial<ChainConfig> = {}): ChainConfig => ({
  rpc: "http://127.0.0.1:1", // never contacted — the chain double owns all I/O
  pool: "0x" + "12".repeat(20),
  startBlock: 0,
  databaseUrl,
  ...extra,
});

const identityOf = (id: ConsumerIdentity): ConsumerWalletIdentity => ({
  keypair: id.spend,
  compressedPubkey: packPubkey(id.spend.publicKey),
  viewKeypair: id.view,
  compressedViewPubkey: packPubkey(id.view.publicKey),
  kemKeypair: { ek: id.kem.publicKey, dk: id.kem.secretKey },
});

const scanIo = (base: string): SelfScanIo => ({
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  events: async (cursor, limit = 5000) => (await get(base, `/events?cursor=${cursor}&limit=${limit}`)).body as any,
  nullifiers: async () => (await get(base, "/nullifiers")).body as string[],
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  head: async () => (await get(base, "/head")).body as any,
  path: async (leafIndex) => {
    const r = await get(base, `/path/${leafIndex}`);
    if (r.status !== 200) throw new Error(`GET /path/${leafIndex} -> ${r.status}`);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return r.body as any;
  },
});

/** Key-order-canonical stringify: the payload JSONB round-trip normalizes
 *  nested object key order (postgres), which is not part of the wire
 *  contract — equality is semantic. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const canon = (x: any): string =>
  Array.isArray(x)
    ? `[${x.map(canon).join(",")}]`
    : x !== null && typeof x === "object"
      ? `{${Object.keys(x).sort().map((k) => `${JSON.stringify(k)}:${canon(x[k])}`).join(",")}}`
      : JSON.stringify(x);

const notesByLeaf = (s: SelfScanState): string =>
  [...s.notes].sort((a, b) => a.leafIndex - b.leafIndex).map((n) => `${n.leafIndex}:${n.value}:${n.spent ? "S" : "u"}`).join(",");

// --- gate-6 inherited vectors (SOLR §3.3.2 served-blob verifier) -------------

interface Disburse256Fixture {
  disclosureElements: string[];
  disclosureHash: string;
  publicsFull: string[];
}

function servedBlobVectors(disFx: Disburse256Fixture): void {
  step("SERVED-BLOB VERIFIER: the gate-6 vectors against packages/core disclosureChain");
  const elements = disFx.disclosureElements.map(BigInt);
  const dh = BigInt(disFx.disclosureHash);
  ok(elements.length === 2054, "disclosure blob is receiverCts[1024] ++ authorityEnvelope[1030]");

  ok(verifyServedDisclosure(elements, dh, 256, "t", 256).status === "verified",
    "the honest served blob refolds to the chain-committed disclosureHash");

  const tampered = [...elements];
  tampered[tampered.length - 1] ^= 1n;
  const tv = verifyServedDisclosure(tampered, dh, 256, "t", 256);
  ok(tv.status === "mismatch" && tv.recomputed !== "0",
    "a tampered last element folds to a different hash -> mismatch");

  // element' = element + r: the same scalar mod r under a different byte
  // encoding — folding it would reproduce the committed hash for bytes the
  // wire must refuse (gate 6's canonical-form rule).
  const aliased = [...elements];
  aliased[0] = elements[0] + FIELD_PRIME;
  const av = verifyServedDisclosure(aliased, dh, 256, "t", 256);
  ok(av.status === "mismatch" && av.recomputed === "0",
    "a non-canonical alias (element + r) is rejected BEFORE folding -> mismatch, no fold ran");

  const swapped = [...elements];
  ok(swapped[0] !== swapped[1], "vector degenerate: equal neighbors");
  swapped[0] = elements[1];
  swapped[1] = elements[0];
  ok(verifyServedDisclosure(swapped, dh, 256, "t", 256).status === "mismatch",
    "swapped adjacent elements change the sequential fold -> mismatch");

  ok(verifyServedDisclosure(elements.slice(0, 1024), dh, 256, "t", 256).status === "unverifiable",
    "a receiver-only truncation cannot complete the chain -> unverifiable");
  ok(verifyServedDisclosure([], dh, 256, "t", 256).status === "withheld",
    "an empty blob -> withheld");
}

// --- consumer leg -------------------------------------------------------------

async function consumerLeg(): Promise<string> {
  const ledger = loadLedger("ledger_consumer.json");
  const dbUrl = await freshDatabase("bongtu_sol_consumer");
  const chain = new FixtureChain(ledger.txs, ledger.batchB);
  const ix = new SolanaIndexer(cfgOf(dbUrl), chain, ledger.programId);

  step("CONSUMER ingest: recorded ledger -> mirror asserted per op against event roots");
  await ix.ingest();
  ok(ix.tree.root() === BigInt(ledger.final.currentRoot), "mirror root == recorded TreeState root at head");
  ok(ix.tree.nextLeafIndex() === ledger.final.nextLeafIndex, `nextLeafIndex == ${ledger.final.nextLeafIndex}`);

  const api = await startApi(ix, 0);
  const base = `http://127.0.0.1:${api.port}`;
  const eventsJson = { value: "" };
  try {
    step("CONSUMER /events: the OPMOD §3.6 discovery feed from instruction data");
    const ev = await get(base, "/events");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const feed = ev.body as any[];
    eventsJson.value = canon(feed);
    ok(feed.map((e) => e.kind).join(",") === "depositPriv,transferPriv,transfer10x2Priv,withdrawPriv",
      `feed kinds in ledger order: ${feed.map((e) => e.kind).join(",")}`);
    ok(feed[1].txHash === feed[2].txHash && feed[1].txHash === ledger.txs[1].signature,
      "transferPriv + transfer10x2Priv ride ONE recorded multi-op tx (FIFO op/event pairing)");
    const depFx = JSON.parse(readFileSync(join(CONFORMANCE, "deposit_priv_fixture.json"), "utf8"));
    const dep = feed[0];
    ok(dep.slices.length === 2 && dep.slices[0].leafIndex === 0 && dep.slices[1].leafIndex === 1,
      "depositPriv slices name leaves @0/@1");
    ok(dep.viewTags.length === 2
      && BigInt(dep.viewTags[0]) === BigInt(depFx.publicsFull[11])
      && BigInt(dep.viewTags[1]) === BigInt(depFx.publicsFull[12]),
      "depositPriv viewTags == the proof's publics");
    ok(dep.kemCiphertexts.length === 2 && dep.kemCiphertexts[0] === depFx.kemCiphertexts[0],
      "per-output kem cts decoded from instruction data");
    ok(BigInt(dep.encryptionNonce) === BigInt(depFx.publicsFull[15]), "nonce == the proof's public");
    ok(dep.epoch === null, "consumer entries carry no arbiter epoch");
    ok(feed[3].kemCiphertexts.length === 1, "withdrawPriv carries its one (change) kem ct");

    step("CONSUMER /nullifiers: the spent set from the self-CPI events");
    const wantNfs = new Set<string>();
    for (const f of ["transfer_priv_fixture.json", "transfer10x2_priv_fixture.json", "withdraw_priv_fixture.json"]) {
      const fx = JSON.parse(readFileSync(join(CONFORMANCE, f), "utf8"));
      for (const nf of fx.nullifiers as string[]) if (BigInt(nf) !== 0n) wantNfs.add(BigInt(nf).toString());
    }
    const nfs = (await get(base, "/nullifiers")).body as string[];
    ok(nfs.length === wantNfs.size && nfs.every((n) => wantNfs.has(n)),
      `nullifier set == the fixtures' nonzero run (${wantNfs.size} entries)`);

    step("CONSUMER /path: single-append leaves fold to the head root");
    const p0 = await get(base, "/path/0");
    ok(p0.status === 200, "GET /path/0 -> 200");
    const p = p0.body as { siblings: string[]; root: string };
    ok(foldToRoot(BigInt(depFx.outputCommitments[0]), p.siblings.map(BigInt), 0) === BigInt(p.root),
      "leaf 0 folds to the served root");

    step("CONSUMER /announcements: the INNER (wrapper-invoked) withdrawPriv rides the feed");
    const wdFx = JSON.parse(readFileSync(join(CONFORMANCE, "withdraw_priv_fixture.json"), "utf8"));
    ok(ledger.txs[2].instructions[0].programId !== ledger.programId,
      "fixture shape: the withdrawPriv op sits ONLY in the inner list, under a foreign wrapper");
    ok(feed[3].announcement !== undefined
      && feed[3].announcement.ephemeralPub === wdFx.stealthEphemeralPub
      && feed[3].announcement.viewTag === wdFx.stealthViewTag,
      "the inner op produced the same withdrawPriv entry a top-level op would (announcement pair intact)");
    ok(feed[3].announcement.recipient === wdFx.recipientTokenAccount,
      "announcement recipient == the proof-bound recipient token account (inner meta 11, not zeroed)");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const ann = (await get(base, "/announcements")).body as any[];
    ok(ann.length === 1 && ann[0].recipient === wdFx.recipientTokenAccount,
      "GET /announcements serves the inner withdraw's recipient");

    step("SELF-SCAN: the unchanged client engine discovers consumer notes from the public feed");
    const io = scanIo(base);
    const r0 = await runSelfScan(io, identityOf(consumerReceiver(0)), EMPTY_SCAN_STATE);
    ok(notesByLeaf(r0) === "0:1000:u,2:600:u,4:700:u",
      `receiver(0) discovers its depositPriv/transferPriv/transfer10x2Priv notes (${notesByLeaf(r0)})`);
    ok(r0.pending.length === 0, "nothing pending on a fully-served consumer ledger");
    const sender = await runSelfScan(io, identityOf(CONSUMER_SENDER), EMPTY_SCAN_STATE);
    ok(notesByLeaf(sender) === "3:400:u,5:300:u,6:100:u",
      `the sender recovers every change note by scan alone (${notesByLeaf(sender)})`);
  } finally {
    await api.stop();
    await ix.close();
  }
  return eventsJson.value;
}

// --- kill-and-resume ----------------------------------------------------------

async function resumeLeg(fullEventsJson: string): Promise<void> {
  const ledger = loadLedger("ledger_consumer.json");
  const dbUrl = await freshDatabase("bongtu_sol_resume");
  const prefix = ledger.txs.slice(0, 2);

  step("RESUME: ingest a prefix, kill, restart against the full ledger");
  const first = new SolanaIndexer(cfgOf(dbUrl), new FixtureChain(prefix, ledger.batchB), ledger.programId);
  await first.ingest();
  ok(first.cursorSignature === prefix[1].signature, "cursor pinned to the last ingested signature");
  await first.close();

  const fullChain = new FixtureChain(ledger.txs, ledger.batchB);
  const resumed = new SolanaIndexer(cfgOf(dbUrl), fullChain, ledger.programId);
  // boot() alone: the rebuilt frontier must equal the RECORDED TreeState at
  // the cursor before any gap tx applies — the resume check, pinned against
  // ledger data rather than the mirror's own arithmetic.
  await resumed.boot();
  ok(resumed.tree.nextLeafIndex() === prefix[1].treeStatePost.nextLeafIndex
    && resumed.tree.root() === BigInt(prefix[1].treeStatePost.currentRoot),
    "restart rebuilt the frontier to the recorded TreeState at the cursor");
  ok(resumed.store.allEvents().length === 3, "the prefix feed entries (deposit + the multi-op pair) came back from Postgres");

  await resumed.ingest();
  ok(fullChain.calls.length === 1 && fullChain.calls[0] === prefix[1].signature,
    "re-ingest asked the chain ONLY for the signature gap (cursor passed as `until`)");
  ok(resumed.tree.root() === BigInt(ledger.final.currentRoot)
    && resumed.tree.nextLeafIndex() === ledger.final.nextLeafIndex,
    "gap replay converges on the recorded head");

  const api = await startApi(resumed, 0);
  try {
    const feed = await get(`http://127.0.0.1:${api.port}`, "/events");
    ok(canon(feed.body) === fullEventsJson,
      "resumed /events serves the single-run ingest's feed verbatim (seqs stable across the restart)");
  } finally {
    await api.stop();
    await resumed.close();
  }
}

// --- dispatch-shape legs (multi-op pairing, chain-ahead heads, arbiter refusal)

async function pairingLeg(): Promise<void> {
  step("PAIRING INVARIANT: an event-stripped multi-op tx throws the op/event imbalance");
  const ledger = loadLedger("ledger_consumer.json");
  const mutated = JSON.parse(JSON.stringify(ledger.txs)) as RecordedTx[];
  ok(mutated[1].instructions.length === 2, "vector shape: the multi-op tx carries two top-level pool ops");
  mutated[1].inner[1] = []; // strip the second op's self-CPI event
  const dbUrl = await freshDatabase("bongtu_sol_pairing");
  const ix = new SolanaIndexer(cfgOf(dbUrl), new FixtureChain(mutated, ledger.batchB), ledger.programId);
  const thrown = await ix.ingest().then(() => null, (e: Error) => e.message);
  ok(thrown !== null && /has 2 ops but 1 events/.test(thrown),
    `the FIFO pairing imbalance fired on the multi-op tx (${thrown})`);
  ok(ix.cursorSignature === null, "and the poisoned range never advanced the cursor");
  await ix.close();
}

/** FixtureChain whose treeHead always reads the FULL recorded head while
 *  txsSince serves only the first `visible` txs — the tx-lands-between-
 *  txsSince-and-account-read race, held stable for the assert. */
class AdvancingChain implements SolanaChainIo {
  readonly calls: (string | null)[] = [];
  visible = 0;
  constructor(private readonly txs: RecordedTx[], private readonly b: number) {}
  async batchSize(): Promise<number> {
    return this.b;
  }
  async treeHead(): Promise<{ root: bigint; nextLeafIndex: number }> {
    const last = this.txs[this.txs.length - 1].treeStatePost;
    return { root: BigInt(last.currentRoot), nextLeafIndex: last.nextLeafIndex };
  }
  async txsSince(untilSignature: string | null): Promise<SolanaLedgerTx[]> {
    this.calls.push(untilSignature);
    const served = this.txs.slice(0, this.visible);
    if (untilSignature === null) return served;
    const at = served.findIndex((t) => t.signature === untilSignature);
    if (at === -1) throw new Error(`AdvancingChain: unknown cursor signature ${untilSignature}`);
    return served.slice(at + 1);
  }
}

async function chainAheadLeg(): Promise<void> {
  step("CHAIN-AHEAD: txs landing between txsSince and the head read are a benign next-poll condition");
  const ledger = loadLedger("ledger_consumer.json");
  const dbUrl = await freshDatabase("bongtu_sol_chainahead");
  const chain = new AdvancingChain(ledger.txs, ledger.batchB);
  chain.visible = 2;
  const ix = new SolanaIndexer(cfgOf(dbUrl), chain, ledger.programId);
  await ix.pollOnce();
  ok(ix.consecutiveFailures === 0 && ix.lastError === null,
    "an ahead TreeState bumps no failure counter — /health stays ok");
  ok(ix.cursorSignature === ledger.txs[1].signature,
    "the applied gap persisted and the cursor advanced despite the ahead head");
  chain.visible = ledger.txs.length;
  await ix.pollOnce();
  ok(ix.consecutiveFailures === 0 && ix.lastError === null, "the catch-up poll stays healthy");
  ok(chain.calls[chain.calls.length - 1] === ledger.txs[1].signature,
    "and asked the chain only for the remaining signature gap");
  ok(ix.tree.root() === BigInt(ledger.final.currentRoot) && ix.tree.nextLeafIndex() === ledger.final.nextLeafIndex,
    "converging on the recorded head");
  await ix.close();
}

async function arbiterRefusalLeg(): Promise<void> {
  step("ARBITER REFUSAL: AUTHORITY_KEY + the Solana backend fails fast at boot");
  const ledger = loadLedger("ledger_consumer.json");
  const thrown = ((): string | null => {
    try {
      new SolanaIndexer(
        cfgOf("postgres://unused", { authorityKey: 1234n }),
        new FixtureChain(ledger.txs, ledger.batchB),
        ledger.programId,
      );
      return null;
    } catch (e) {
      return (e as Error).message;
    }
  })();
  ok(thrown === "AUTHORITY_KEY is set but arbiter surfaces are not yet supported on the Solana backend — unset AUTHORITY_KEY (public mode) or run the EVM backend for arbiter mode",
    "the pinned refusal message (no silent /notes 503, no vanished envelope alarms)");
  ok(thrown !== null && !thrown.includes("1234"), "the message carries no key material");
}

// --- enterprise leg: disclosure serving + alarm mapping ----------------------

async function enterpriseLeg(disFx: Disburse256Fixture): Promise<void> {
  const ledger = loadLedger("ledger_enterprise.json");
  const elements = disFx.disclosureElements;

  step("ENTERPRISE ingest: the served blob verifies against the chain-committed hash at ingest");
  const dir = mkdtempSync(join(tmpdir(), "bongtu-disclosure-"));
  writeFileSync(join(dir, "256.json"), JSON.stringify(elements));
  const dbUrl = await freshDatabase("bongtu_sol_enterprise");
  const ix = new SolanaIndexer(cfgOf(dbUrl, { disclosureDir: dir }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await ix.ingest();
  ok(ix.tree.root() === BigInt(ledger.final.currentRoot) && ix.tree.nextLeafIndex() === ledger.final.nextLeafIndex,
    "mirror == recorded head across deposit -> disburse256 attach -> appends after the batch");

  const api = await startApi(ix, 0);
  const base = `http://127.0.0.1:${api.port}`;
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const feed = (await get(base, "/events")).body as any[];
    ok(feed.map((e) => e.kind).join(",") === "deposit,disburse,withdraw,transfer,transfer10x2",
      `enterprise feed kinds: ${feed.map((e) => e.kind).join(",")}`);
    const dis = feed[1];
    ok(dis.disclosure === "verified" && dis.batchId === 256 && dis.epoch === 0,
      "disburse entry: served blob verified, batchId = the attach start, genesis epoch");
    ok(BigInt(dis.ecdhPublicKey[0]) === BigInt(disFx.publicsFull[0])
      && BigInt(dis.encryptionNonce) === BigInt(disFx.publicsFull[8]),
      "disburse ecdh + nonce == the proof's publics");
    ok(dis.ciphertext.length === 0, "no disclosure bytes on the feed — they are institution-served (SOLR §3.3.2)");
    const tr = feed[3];
    ok(tr.slices.length === 3 && tr.slices[2].elts === 16 && tr.ciphertext.length === 24,
      "enterprise transfer feed shape == the EVM entry (receivers[8] ++ authority[16])");

    step("ENTERPRISE GET /disclosure: any party can refold the served bytes");
    const served = await get(base, "/disclosure/256");
    ok(served.status === 200, "GET /disclosure/256 -> 200 (held blob, passing verdict)");
    const blob = served.body as { startLeafIndex: number; elements: string[]; disclosureHash: string; verdict: string };
    ok(blob.verdict === "verified" && BigInt(blob.disclosureHash) === BigInt(disFx.disclosureHash),
      "the body carries the registry verdict and the chain-committed disclosureHash");
    ok(blob.elements.length === 2054
      && BigInt(blob.elements[0]) === BigInt(elements[0])
      && BigInt(blob.elements[2053]) === BigInt(elements[2053]),
      "the served blob is the 2054-element disclosure array, fold order");
    ok((await get(base, "/disclosure/512")).status === 404, "an unknown batch -> 404");

    step("ENTERPRISE /alarms + /path + /nullifiers");
    ok(((await get(base, "/alarms")).body as unknown[]).length === 0, "no alarms on the honest run");
    ok((await get(base, "/path/300")).status === 422, "a batch-interior leaf stays 422 in public mode");
    ok((await get(base, "/path/0")).status === 200 && (await get(base, "/path/512")).status === 200,
      "single-append leaves serve before and after the batch");
    const nfs = (await get(base, "/nullifiers")).body as string[];
    ok(nfs.length === 15, `spent set = 1 disburse + 2 withdraw + 2 transfer + 10 transfer10x2 (got ${nfs.length})`);
  } finally {
    await api.stop();
    await ix.close();
  }

  step("ENTERPRISE restart: the boot invariant re-checks the served blob per batch");
  const again = new SolanaIndexer(cfgOf(dbUrl, { disclosureDir: dir }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await again.boot();
  ok(again.disclosures.blobOf(256) !== null, "restart re-loads + re-verifies the blob from the institution dir");
  ok(again.disclosures.alarms(Math.floor(Date.now() / 1000)).length === 0, "a passing re-check raises nothing");
  await again.close();
}

async function rotationTripwireLeg(): Promise<void> {
  step("ROTATION TRIPWIRE: a non-genesis disburse epoch fails ingest loudly (issue #44)");
  // Enterprise transfer feed entries pin the genesis arbiter epoch because op
  // events carry no epoch field; the disburse event is the one ledger signal
  // that can disprove the pin. Patch the recorded disburse event's epoch
  // (u64 LE payload tail, byte offset 170) to 1 and expect ingest to refuse.
  const ledger = loadLedger("ledger_enterprise.json");
  const txs = JSON.parse(JSON.stringify(ledger.txs)) as RecordedTx[];
  const DISBURSE_EVENT_HEX_LEN = 2 + 2 * (2 + 8 + 5 * 32 + 8);
  const patched = txs.flatMap((tx) =>
    tx.inner.flatMap((list) =>
      list.filter((r) => r.data.length === DISBURSE_EVENT_HEX_LEN && parseInt(r.data.slice(2, 4), 16) === EVENT_DISCRIMINATOR),
    ),
  );
  ok(patched.length === 1, "exactly one recorded disburse event to patch");
  patched[0].data = patched[0].data.slice(0, 2 + 2 * 170) + "0100000000000000";
  const dbUrl = await freshDatabase("bongtu_sol_tripwire");
  const ix = new SolanaIndexer(cfgOf(dbUrl), new FixtureChain(txs, ledger.batchB), ledger.programId);
  const thrown = await ix.ingest().then(
    () => null,
    (e) => (e as Error).message,
  );
  await ix.close();
  ok(thrown !== null && thrown.startsWith("solana ingest: batch at leaf 256 records arbiter epoch 1; this backend pins the genesis epoch"),
    `ingest refuses the non-genesis batch (got: ${thrown})`);
}

async function tamperedBlobLeg(disFx: Disburse256Fixture): Promise<void> {
  step("ALARM MAPPING: a tampered served blob -> the existing mismatch class");
  const ledger = loadLedger("ledger_enterprise.json");
  const dir = mkdtempSync(join(tmpdir(), "bongtu-disclosure-tampered-"));
  const tampered = [...disFx.disclosureElements];
  tampered[tampered.length - 1] = "0x" + (BigInt(tampered[tampered.length - 1]) ^ 1n).toString(16).padStart(64, "0");
  writeFileSync(join(dir, "256.json"), JSON.stringify(tampered));
  const dbUrl = await freshDatabase("bongtu_sol_tampered");
  const ix = new SolanaIndexer(cfgOf(dbUrl, { disclosureDir: dir }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await ix.ingest();
  const api = await startApi(ix, 0);
  const base = `http://127.0.0.1:${api.port}`;
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const feed = (await get(base, "/events")).body as any[];
    ok(feed[1].disclosure === "mismatch", "the disburse entry reads mismatch");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const alarms = (await get(base, "/alarms")).body as any[];
    ok(alarms.length === 1 && alarms[0].type === "disclosure" && alarms[0].status === "mismatch"
      && alarms[0].startLeafIndex === 256,
      "ONE discriminated {type: disclosure, status: mismatch} alarm for the batch");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(((await get(base, "/health")).body as any).alarms === 1, "/health counts it");
    const served = await get(base, "/disclosure/256");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const body = served.body as any;
    ok(served.status === 409 && body.verdict === "mismatch" && BigInt(body.disclosureHash) === BigInt(disFx.disclosureHash),
      "GET /disclosure serves the tampered bytes 409 with verdict + committed hash, never a clean 200");
    ok(Array.isArray(body.elements) && body.elements.length === 2054,
      "the bytes still serve (refold evidence), flagged");
  } finally {
    await api.stop();
    await ix.close();
  }
}

async function tamperAfterIngestLeg(disFx: Disburse256Fixture): Promise<void> {
  step("TAMPER AFTER INGEST: a blob swapped after a verified ingest surfaces at the next boot");
  const ledger = loadLedger("ledger_enterprise.json");
  const dir = mkdtempSync(join(tmpdir(), "bongtu-disclosure-swap-"));
  writeFileSync(join(dir, "256.json"), JSON.stringify(disFx.disclosureElements));
  const dbUrl = await freshDatabase("bongtu_sol_swapped");
  const first = new SolanaIndexer(cfgOf(dbUrl, { disclosureDir: dir }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await first.ingest();
  ok(first.store.allEvents()[1].disclosure?.status === "verified", "the honest blob baked a verified verdict at ingest");
  await first.close();

  const tampered = [...disFx.disclosureElements];
  tampered[0] = "0x" + (BigInt(tampered[0]) ^ 1n).toString(16).padStart(64, "0");
  writeFileSync(join(dir, "256.json"), JSON.stringify(tampered));

  const again = new SolanaIndexer(cfgOf(dbUrl, { disclosureDir: dir }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await again.ingest();
  const api = await startApi(again, 0);
  const base = `http://127.0.0.1:${api.port}`;
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const alarms = (await get(base, "/alarms")).body as any[];
    ok(alarms.length === 1 && alarms[0].type === "disclosure" && alarms[0].status === "mismatch"
      && alarms[0].startLeafIndex === 256,
      "the boot recompute conflict raises ONE registry-owned mismatch alarm");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(((await get(base, "/health")).body as any).alarms === 1, "/health counts it");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const feed = (await get(base, "/events")).body as any[];
    ok(feed[1].disclosure === "mismatch",
      "/events projects the registry's CURRENT verdict, not the stale baked one");
    const served = await get(base, "/disclosure/256");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(served.status === 409 && (served.body as any).verdict === "mismatch",
      "GET /disclosure refuses a clean 200 for the swapped bytes");
  } finally {
    await api.stop();
    await again.close();
  }
}

async function withheldBlobLeg(disFx: Disburse256Fixture): Promise<void> {
  step("ALARM MAPPING: non-serving past grace -> withheld; a late blob resolves it");
  const ledger = loadLedger("ledger_enterprise.json");
  const dbUrl = await freshDatabase("bongtu_sol_withheld");
  // The recorded blockTime is a fixed past instant, so "inside the grace
  // window" needs a grace wide enough to cover fixture-age against real now;
  // "past grace" is the deterministic -1 flip, same as the kem transport leg.
  const WIDE_GRACE = 1_000_000_000_000;
  const ix = new SolanaIndexer(cfgOf(dbUrl, { disclosureGraceSeconds: WIDE_GRACE }), new FixtureChain(ledger.txs, ledger.batchB), ledger.programId);
  await ix.ingest();
  const api = await startApi(ix, 0);
  const base = `http://127.0.0.1:${api.port}`;
  try {
    ok(((await get(base, "/alarms")).body as unknown[]).length === 0,
      "inside the grace window an unserved blob is operational, not an alarm");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(((await get(base, "/events")).body as any[])[1].disclosure === undefined,
      "the disburse entry carries no verdict yet");
    ok((await get(base, "/disclosure/256")).status === 404, "nothing to serve");

    // grace -1 makes any unserved batch read withheld deterministically —
    // the same seam-flip the kem transport test uses.
    ix.disclosures.graceSeconds = -1;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const alarms = (await get(base, "/alarms")).body as any[];
    ok(alarms.length === 1 && alarms[0].type === "disclosure" && alarms[0].status === "withheld"
      && alarms[0].startLeafIndex === 256,
      "past grace the unserved batch alarms {type: disclosure, status: withheld}");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(((await get(base, "/events")).body as any[])[1].disclosure === "withheld",
      "/events projects the same past-grace verdict");
    ix.disclosures.graceSeconds = WIDE_GRACE;

    const verdict = ix.disclosures.loadBlob(256, disFx.disclosureElements.map(BigInt), 256);
    ok(verdict !== null && verdict.status === "verified", "a late-served blob verifies against the recorded anchor");
    ok(((await get(base, "/alarms")).body as unknown[]).length === 0, "the withheld alarm clears once valid bytes are served");
    const late = await get(base, "/disclosure/256");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ok(late.status === 200 && (late.body as any).verdict === "verified", "and GET /disclosure serves them 200 with the verdict");
  } finally {
    await api.stop();
    await ix.close();
  }
}

async function main(): Promise<void> {
  const disFx = JSON.parse(readFileSync(join(CONFORMANCE, "disburse256_fixture.json"), "utf8")) as Disburse256Fixture;

  servedBlobVectors(disFx);
  const fullEventsJson = await consumerLeg();
  await resumeLeg(fullEventsJson);
  await pairingLeg();
  await chainAheadLeg();
  await arbiterRefusalLeg();
  await enterpriseLeg(disFx);
  await rotationTripwireLeg();
  await tamperedBlobLeg(disFx);
  await tamperAfterIngestLeg(disFx);
  await withheldBlobLeg(disFx);

  console.log(`\nSOLANA BACKEND LEG: ${failures.count === 0 ? "ALL PASS" : `${failures.count} FAILURES`}`);
  process.exit(failures.count === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error("\nSOLANA BACKEND LEG ERROR:", e && e.stack ? e.stack : e);
  process.exit(1);
});
